import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { FaHome , FaGithub} from "react-icons/fa";
import {SiCodeproject} from "react-icons/si"
import {IoIosContact} from "react-icons/io"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Shreejan Dolai</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section className="bg-cyan-900 min-h-screen flex flex-row">
          <div className="mx-8fixed top-0 left-0 h-screen w-16 max-md:w-32 max-ssm:w-52 max-xlsm:w-60 m-0 flex flex-col bg-gray-800  ">
            <SideBarIcon icon={<FaHome size="20" />} text={"Home"} />
            <SideBarIcon
              icon={<SiCodeproject size="20" />}
              text={"See projects"}
            />
            <SideBarIcon
              icon={<FaGithub size="20" />}
              text={"Edit the page in github"}
            />
            <SideBarIcon
              icon={<IoIosContact size="28" />}
              text={"Contact Me"}
            />
          </div>
          <div className="mx-4 justify-center align-middle text-center my-5">
            <figure class="flex flex-row-reverse md:flex rounded-xl p-8 bg-cyan-800 border-2 border-solid border-gray-800 md:p-0 dark:bg-slate-800">
              <img
                class="w-24 h-24 md:w-48 md:h-auto md:rounded-none rounded-full mx-auto"
                src="https://avatars.githubusercontent.com/u/93109967?v=4"
                alt=""
                width="384"
                height="512"
              />
              <div class="pt-6 md:p-8 text-center md:text-left space-y-4">
                <blockquote>
                  <p class="text-lg font-medium text-center">
                    “Hello all, I'm Shreejan Dolai. I am from India, West Bengal. This is my portfolio which tells you what are my skills, hobbies, projects, degrees, and many more. I like to help people and always want to improve my skills.”
                  </p>
                </blockquote>
                <figcaption class="font-medium">
                  <div class="text-sky-500 dark:text-sky-400">Shreejan Dolai</div>
                  <div class="text-slate-700 dark:text-slate-500">
                    Student
                  </div>
                </figcaption>
              </div>
            </figure>
          </div>
        </section>
      </main>
    </div>
  );
}

const SideBarIcon = ({icon, text}) => {
  return (
  <div className="sidebar-icon group">
    {icon}

    <span className="sidebar-tooltip group-hover:scale-100">
      {text}
    </span>
  </div> 
  );
};