import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import Header from "./Header";
// import Intro from "./Intro";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Shreejan Dolai</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section className="bg-stone-800 h-screen px-10">
          <Header />
          {/* <Intro /> */}
        </section>
      </main>
    </div>
  );
}